src/BackBundle/Entity/Planche.php
<?php

namespace BackBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Planche
 *
 * @ORM\Table(name="planche")
 * @ORM\Entity(repositoryClass="BackBundle\Repository\PlancheRepository")
 */
class Planche
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="reference", type="string", length=255)
     */
    private $reference;

    /**
     * @var float
     *
     * @ORM\Column(name="longueur", type="float")
     */
    private $longueur;

    /**
     * @var float
     *
     * @ORM\Column(name="largeur", type="float")
     */
    private $largeur;

    /**
     * @var float
     *
     * @ORM\Column(name="epaisseur", type="float")
     */
    private $epaisseur;

    /**
     * @var string
     *
     * @ORM\Column(name="emplacement", type="string", length=255)
     */
    private $emplacement;

    /**
     * @var float
     *
     * @ORM\Column(name="prix", type="float")
     */
    private $prix;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     *
     * @ORM\ManyToOne(targetEntity="Couleur", inversedBy="planches")
     */
    private $couleur;

    /**
     *
     * @ORM\OneToMany(targetEntity="Photo", mappedBy="planche")
     */
    private $photos;

    /**
     *
     * @ORM\ManyToOne(targetEntity="Essence", inversedBy="planche")
     */
    private $essence;

    /**
     * @var float
     *
     * @ORM\Column(name="humidite", type="float")
     */
    private $humidite;

    /**
     * @var int
     *
     * @ORM\Column(name="durete", type="integer")
     */
    private $durete;

    /**
     * @var string
     *
     * @ORM\Column(name="taille", type="string")
     */
    private $taille;

    /**
     * @var integer
     *
     * @ORM\Column(name="stock_mini", type="integer")
     */
    private $stock_mini;

    /**
     * @var integer
     *
     * @ORM\Column(name="stock_alerte", type="integer")
     */
    private $stock_alerte;

    /**
     * @var integer
     *
     * @ORM\Column(name="stock", type="integer")
     */
    private $stock;

    /**
     * @var int
     *
     * @ORM\Column(name="nb_commandes", type="integer")
     */
    private $nb_commandes;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_reapro_dernier", type="datetime")
     */
    private $date_reapro_dernier;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_reapro_prochain", type="datetime")
     */
    private $date_reapro_prochain;
    
    /**
     * @var float
     *
     * @ORM\Column(name="poids", type="float")
     */
    private $poids;

    /**
     * @ORM\OneToOne(targetEntity="ProduitGenerique", mappedBy="planche")
     */
    private $produitGenerique;


    /**
     * Constructor
     */
    public function __construct()
    {
        $this->photos = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get Classname
     *
     * @return string
     */
    public function getClassName()
    {
        return 'Planche';
    }

    /**
     * Get PhotoPrincipal
     *
     * @return string
     */
    public function getPhotoPrincipale()
    {
        $res = "";

        foreach ($this->photos as $photo){
            if ($photo -> getEstPrincipal() === true){
                $res  =  $photo;
            }
        }

        return $res;
    }

    public function __toString(){
        return 'pl'.$this->reference;
    }

    /**
     * Set couleur
     *
     * @param \BackBundle\Entity\Couleur $couleur
     * @return Planche
     */
    public function setCouleur(\BackBundle\Entity\Couleur $couleur = null)
    {
        $this->couleur = $couleur;

        return $this;
    }

    /**
     * Get couleur
     *
     * @return \BackBundle\Entity\Couleur
     */
    public function getCouleur()
    {
        return $this->couleur;
    }

    /**
     * Add photos
     *
     * @param \BackBundle\Entity\Photo $photos
     * @return Planche
     */
    public function addPhoto(\BackBundle\Entity\Photo $photos)
    {
        $this->photos[] = $photos;

        return $this;
    }

    /**
     * Remove photos
     *
     * @param \BackBundle\Entity\Photo $photos
     */
    public function removePhoto(\BackBundle\Entity\Photo $photos)
    {
        $this->photos->removeElement($photos);
    }

    /**
     * Get photos
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPhotos()
    {
        return $this->photos;
    }

    /**
     * Get photoNonPrincipal
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPhotosNonPrincipal()
    {
        $res=[];
        foreach($this->photos as $photo) {
            if(!$photo->getEstPrincipal()){
                $res[] = $photo;
            }
        }
        return $res;
    }

    /**
     * Set essence
     *
     * @param \BackBundle\Entity\Essence $essence
     * @return Planche
     */
    public function setEssence(\BackBundle\Entity\Essence $essence = null)
    {
        $this->essence = $essence;

        return $this;
    }

    /**
     * Get essence
     *
     * @return \BackBundle\Entity\Essence 
     */
    public function getEssence()
    {
        return $this->essence;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Planche
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set reference
     *
     * @param string $reference
     * @return Planche
     */
    public function setReference($reference)
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * Get reference
     *
     * @return string 
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * Set longueur
     *
     * @param float $longueur
     * @return Planche
     */
    public function setLongueur($longueur)
    {
        $this->longueur = $longueur;

        return $this;
    }

    /**
     * Get longueur
     *
     * @return float 
     */
    public function getLongueur()
    {
        return $this->longueur;
    }

    /**
     * Set largeur
     *
     * @param float $largeur
     * @return Planche
     */
    public function setLargeur($largeur)
    {
        $this->largeur = $largeur;

        return $this;
    }

    /**
     * Get largeur
     *
     * @return float 
     */
    public function getLargeur()
    {
        return $this->largeur;
    }

    /**
     * Set epaisseur
     *
     * @param float $epaisseur
     * @return Planche
     */
    public function setEpaisseur($epaisseur)
    {
        $this->epaisseur = $epaisseur;

        return $this;
    }

    /**
     * Get epaisseur
     *
     * @return float 
     */
    public function getEpaisseur()
    {
        return $this->epaisseur;
    }

    /**
     * Set emplacement
     *
     * @param string $emplacement
     * @return Planche
     */
    public function setEmplacement($emplacement)
    {
        $this->emplacement = $emplacement;

        return $this;
    }

    /**
     * Get emplacement
     *
     * @return string 
     */
    public function getEmplacement()
    {
        return $this->emplacement;
    }

    /**
     * Set prix
     *
     * @param float $prix
     * @return Planche
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * Get prix
     *
     * @return float 
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Planche
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set humidite
     *
     * @param float $humidite
     * @return Planche
     */
    public function setHumidite($humidite)
    {
        $this->humidite = $humidite;

        return $this;
    }

    /**
     * Get humidite
     *
     * @return float 
     */
    public function getHumidite()
    {
        return $this->humidite;
    }

    /**
     * Set durete
     *
     * @param \int $durete
     * @return Planche
     */
    public function setDurete($durete)
    {
        $this->durete = $durete;

        return $this;
    }

    /**
     * Get durete
     *
     * @return \int 
     */
    public function getDurete()
    {
        return $this->durete;
    }

    /**
     * Set taille
     *
     * @param string $taille
     * @return Planche
     */
    public function setTaille($taille)
    {
        $this->taille = $taille;

        return $this;
    }

    /**
     * Get taille
     *
     * @return string 
     */
    public function getTaille()
    {
        return $this->taille;
    }

    /**
     * Set nb_commandes
     *
     * @param \int $nbCommandes
     * @return Planche
     */
    public function setNbCommandes($nbCommandes)
    {
        $this->nb_commandes = $nbCommandes;

        return $this;
    }

    /**
     * Get nb_commandes
     *
     * @return \int 
     */
    public function getNbCommandes()
    {
        return $this->nb_commandes;
    }

    /**
     * Set date_reapro_dernier
     *

src/BackBundle/Form/PlancheType.php
<?php

namespace BackBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlancheType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('nom')->add('reference')->add('longueur')->add('largeur')->add('epaisseur')
            ->add('emplacement')->add('prix')->add('description')->add('humidite')->add('durete')
            ->add('taille')->add('stock_mini')->add('stock_alerte')->add('stock')
            ->add('nb_commandes')->add('date_reapro_dernier', null,array('widget' => 'single_text',
                'input' => 'datetime','attr' => array('class' => 'date-pick')))->add('date_reapro_prochain', null,array('widget' => 'single_text',
        'input' => 'datetime','attr' => array('class' => 'date-pick')))
        ->add('poids')->add('essence');
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'BackBundle\Entity\Planche'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'backbundle_planche';
    }


}

src/BackBundle/Controller/PlancheController.php
<?php

namespace BackBundle\Controller;

use BackBundle\Entity\Photo;
use BackBundle\Entity\Planche;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

/**
 * Planche controller.
 *
 * @Route("planche")
 */
class PlancheController extends Controller
{
    /**
     * Lists all planche entities.
     *
     * @Route("/", name="planche_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $planches = $em->getRepository('BackBundle:Planche')->findAll();

        return $this->render('BackBundle:planche:index.html.twig', array(
            'planches' => $planches,
        ));
    }

    /**
     * Creates a new planche entity.
     *
     * @Route("/new", name="planche_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $planche = new Planche();
        $form = $this->createForm('BackBundle\Form\PlancheType', $planche);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($planche);
            $em->flush($planche);

            return $this->redirectToRoute('planche_show', array('id' => $planche->getId()));
        }

        return $this->render('BackBundle:planche:new.html.twig', array(
            'planche' => $planche,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a planche entity.
     *
     * @Route("/{id}", name="planche_show")
     * @Method("GET")
     */
    public function showAction(Planche $planche)
    {
        $deleteForm = $this->createDeleteForm($planche);

        return $this->render('BackBundle:planche:show.html.twig', array(
            'planche' => $planche,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing planche entity.
     *
     * @Route("/{id}/edit", name="planche_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Planche $planche)
    {
        $deleteForm = $this->createDeleteForm($planche);
        $editForm = $this->createForm('BackBundle\Form\PlancheType', $planche);
        $editForm->handleRequest($request);

        /* images */
        $em = $this->getDoctrine()->getManager();
        $images = $em->getRepository('BackBundle:Photo')->findAll();
        $couleurs = $em->getRepository('BackBundle:Couleur')->findAll();

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('planche_edit', array('id' => $planche->getId()));
        }

        return $this->render('BackBundle:planche:editCustom.html.twig', array(
            'images' => $images,
            'planche' => $planche,
            'couleurs' => $couleurs,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a planche entity.
     *
     * @Route("/suppression/{id}", name="planche_delete")
     * @Method({"GET", "DELETE"})
     */
    public function deleteAction(Request $request, Planche $planche)
    {
    $em = $this->getDoctrine()->getManager();
    $em->remove($planche);
    $em->flush();

        return $this->redirectToRoute('planche_index');
    }

    /**
     * Creates a form to delete a planche entity.
     *
     * @param Planche $planche The planche entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Planche $planche)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('planche_delete', array('id' => $planche->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }


    /**
     * Add Image
     * @Route("/addImage/{idPlanche}/{idPhoto}/{isMain}", name="planche_addImage")
     * @ParamConverter("planche", options={"mapping": {"idPlanche": "id"}})
     * @ParamConverter("photo", options={"mapping": {"idPhoto": "id"}})
     */
    public function addImage(Planche $planche,Photo $photo, $isMain)
    {
        $em = $this->getDoctrine()->getManager();
        $photo->setPlanche($planche);
        $photo->setEstPrincipal($isMain);
        $em->persist($photo);
        $em->flush();
        return $this->redirectToRoute("planche_edit", array("id"=>$planche->getId()));
    }

    /**
     * Add Image
     * @Route("/addImage/{idPlanche}/{idPhoto}", name="planche_removeImage")
     * @ParamConverter("planche", options={"mapping": {"idPlanche": "id"}})
     * @ParamConverter("photo", options={"mapping": {"idPhoto": "id"}})
     */
    public function removeImage(Planche $planche,Photo $photo)
    {
        $em = $this->getDoctrine()->getManager();
        $photo->setPlanche(null);
        $em->persist($photo);
        $em->flush();
        return $this->redirectToRoute("planche_edit", array("id"=>$planche->getId()));
    }

}

src/BackBundle/Resources/views/planche/edit.html.twig
{% extends 'BackBundle:layout:baseBack.html.twig' %}

{% block body %}
    <h1>Planche | Édition</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input class="btn btn-default" type="submit" value="Modifier" />
    {{ form_end(edit_form) }}

    <ul class="actions">
        <li>
            <a href="{{ path('planche_index') }}">Retour</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                <input class="btn btn-default pull-right" type="submit" value="Supprimer">
            {{ form_end(delete_form) }}
        </li>
    </ul>{% endblock %}
{% block javascript %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-timepicker-addon.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css">
    <script src="https://cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-sliderAccess.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $('.date-pick').datetimepicker({
                timeFormat: 'HH:mm:ss',
                stepHour: 2,
                stepMinute: 10,
                stepSecond: 10
            });
        });
    </script>
{% endblock %}

src/BackBundle/Resources/views/planche/editCustom.html.twig
{% extends 'BackBundle:layout:baseBack.html.twig' %}

{% block body %}
    <h1>Planche | Édition</h1>

    <div class="row">
        <div class="col-md-6">
            {{ form_start(edit_form) }}
            {{ form_widget(edit_form) }}
            <input class="btn btn-default" type="submit" value="Modifier"/>
            {{ form_end(edit_form) }}
        </div>
        <div class="col-md-6">
            <h3>Les photos</h3>
            <div class="well">
                <h4>Attribuées</h4>
                <div class="row">
                    {% if planche.photoPrincipale is defined and not planche.photoPrincipale == "" %}
                        <div class="col-md-2">
                            <div class="panel panel-default">
                                <div class="panel-heading"><h6>Principale</h6></div>
                                <div class="panel-body">
                                    <img class="img img-rounded"     src="{{ vich_uploader_asset(planche.photoPrincipale , 'imageFile') }}">
                                </div>
                                <div class="panel-footer">
                                    <a href="{{ path('planche_removeImage', {"idPlanche":planche.id, "idPhoto":planche.photoPrincipale.id}) }}">Enlever</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    {% for photo in planche.photosNonPrincipal %}
                        <div class="col-md-2">
                            <div class="panel">
                                <img class="img img-rounded" src="{{ vich_uploader_asset(photo , 'imageFile') }}">
                                <div class="panel-footer">
                                    <a href="{{ path('planche_removeImage', {"idPlanche":planche.id, "idPhoto":photo.id}) }}">Enlever</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="well">
                <h4>Disponibles</h4>
                <div class="row">
                    {% for image in images %}
                        {% if image.planche != planche %}
                            <div class="col-md-2">
                                <div class="panel">
                                    <img class="img img-rounded" src="{{ vich_uploader_asset(image , 'imageFile') }}">
                                    <div class="panel-footer">
                                        <a href="{{ path('planche_addImage', {"idPlanche":planche.id, "idPhoto":image.id, "isMain":1}) }}">Principale</a>
                                        <a href="{{ path('planche_addImage', {"idPlanche":planche.id, "idPhoto":image.id, "isMain":0}) }}">Normale</a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

            <h3>Les couleurs</h3>
            <div class="well">
                <h4>Attribuée</h4>
                <div class="row">
                    {% if planche.couleur is defined and not planche.couleur == "" %}
                        <div class="col-md-2">
                            <div class="panel">
                                <div class="panel-body" style="background: {{ planche.couleur.hexa }};"></div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="well">
                <h4>Disponibles</h4>
                <div class="row">
                    {% for couleur in couleurs %}
                        <div class="col-md-2">
                            <div class="panel">
                                <a href="{{ path('addCouleur', {"class":"planche", "obj":planche.id, "idCouleur":couleur.id}) }}"><div class="panel-body" style="background: {{ couleur.hexa }};"></div></a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <ul class="actions">
        <li>
            <a href="{{ path('planche_index') }}">Retour</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
            <input class="btn btn-default pull-right" type="submit" value="Supprimer">
            {{ form_end(delete_form) }}
        </li>
    </ul>


{% endblock %}
{% block javascript %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-timepicker-addon.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css">
    <script src="https://cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-sliderAccess.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $('.date-pick').datetimepicker({
                timeFormat: 'HH:mm:ss',
                stepHour: 2,
                stepMinute: 10,
                stepSecond: 10
            });
        });
    </script>
{% endblock %}

src/BackBundle/Resources/views/planche/index.html.twig
{% extends 'BackBundle:layout:baseBack.html.twig' %}

    {% block body %}
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h1>Planches</h1>
                    </div>
                    <div class="box-body">
                        <table id="tab-data" class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>Photo</th>

                                <th>Nom - Reference</th>

                                <th>Emplacement</th>

                                <th>Prix</th>

                                <th>Stock mini</th>

                                <th>Stock alerte</th>

                                <th>Stock</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for planche in planches %}
                                <tr>
                                    <td>
                                        {% if planche.photoPrincipale is defined and not planche.photoPrincipale == "" %}
                                            <a href="{{ path('planche_show', { 'id': planche.id }) }}"><img
                                                        class="img img-circle imgThumb"
                                                        src="{{ vich_uploader_asset(planche.photoPrincipale , 'imageFile') }}"></a>
                                        {% endif %}
                                    </td>
                                    <td>{{ planche.nom }} - {{ planche.reference }}</td>
                                    <td>{{ planche.emplacement }}</td>
                                    <td>{{ planche.prix }}</td>
                                    <td>{{ planche.stockmini }}</td>
                                    <td>{{ planche.stockalerte }}</td>
                                    <td>{{ planche.stock }}</td>
                                    <td>

                                        <a href="{{ path('planche_show', { 'id': planche.id }) }}"
                                           class="action val-est-un-narvalo">

                                            <i class="fa fa-eye"></i>

                                        </a>

                                        <a href="{{ path('planche_edit', { 'id': planche.id }) }}"
                                           class="action val-est-un-narvalo">

                                            <i class="fa fa-pencil"></i>

                                        </a>
                                        <a href="{{ path('planche_delete', { 'id': planche.id }) }}"
                                           class="action val-est-un-narvalo">


                                            <i class="fa fa-trash"></i>

                                        </a>


                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <ul class="actions">
            <li>
                <a class="btn btn-default" href="{{ path('planche_new') }}">Ajouter un(e) Planche</a>
            </li>
        </ul>
    {% endblock %}

    {% block javascript %}
        <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
        <script>
            $(function () {
                $("#tab-data").DataTable({
                    "ordering": true,
                    "paging": true,
                    "lengthChange": true,
                    "info": true,
                    "scrollX": true,
                    "autoWidth": false

                });
            });
        </script>
    {% endblock %}

src/BackBundle/Resources/views/planche/new.html.twig
    {% extends 'BackBundle:layout:baseBack.html.twig' %}

{% block body %}
    <h1>Planche | Création</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <input class="btn btn-default" type="submit" value="Créer" />
    {{ form_end(form) }}

    <ul class="actions">
        <li>
            <a href="{{ path('planche_index') }}">Retour</a>
        </li>
    </ul>{% endblock %}
    {% block javascript %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>
        <script src="https://cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-timepicker-addon.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css">
        <script src="https://cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-sliderAccess.js"></script>
        <script type="text/javascript">
            $( document ).ready(function() {
                $('.date-pick').datetimepicker({
                    timeFormat: 'HH:mm:ss',
                    stepHour: 2,
                    stepMinute: 10,
                    stepSecond: 10
                });
            });
        </script>
    {% endblock %}